### ISSUE TITLE
Question about the stellar mass in mass_cumul_z8.dat

### ISSUE THREAD

**Issue by HoisW** [mrbk/JWST_MstarDensity#1]
Dear Professor, 
I have a question and would like to request your assistance. In the file mass_cumul_z8.dat, the mass_limit array is as follows: [1.07e+10, 1.37e+10, 1.52e+10, 5.46e+10]. The first three data points correspond to id 2859, 13050, and 11184 (at redshifts 8.11, 8.14, and 7.32 respectively) in Extended Data Table 2 of https://www.nature.com/articles/s41586-023-05786-2. However, I am unsure how the last data point in mass_limit, 5.46e+10, was obtained. Why was this value used instead of the stellar mass at redshift 7.48 in Extended Data Table 2?  Any help is appreciated. Thanks in advance!

**Comment by HoisW** [comment]
I see. Lensing indicates a relatively modest −0.15 dex correction to the stellar mass of 38094.

**Comment by mrbk** [comment]
The data files mass_cumul_z8.dat (and z9.dat) came directly from Dr. Ivo Labbe so that I could directly compare with their results, so any questions about the precise mass limits in the file would have to be directed to him.

Best regards,
Mike


--
Mike Boylan-Kolchin
Associate Professor  |  Department of Astronomy
The University of Texas at Austin
office: +1.512.471.3343
https://mrbk.github.io<https://www.as.utexas.edu/~mbk>

On May 13, 2023, at 11:14 PM, HoisW ***@***.***> wrote:



Dear Professor,
I have a question and would like to request your assistance. In the file mass_cumul_z8.dat, the mass_limit array is as follows: [1.07e+10, 1.37e+10, 1.52e+10, 5.46e+10]. The first three data points correspond to id 2859, 13050, and 11184 (at redshifts 8.11, 8.14, and 7.32 respectively) in Extended Data Table 2 of https://www.nature.com/articles/s41586-023-05786-2. However, I am unsure how the last data point in mass_limit, 5.46e+10, was obtained. Why was this value used instead of the stellar mass at redshift 7.48 in Extended Data Table 2? Any help is appreciated. Thanks in advance!

**Comment by HoisW** [comment]
Thank you very much for your reply! If the data is directly from Dr. Ivo Labbe, this reminds me of another issue pointed out by N. Menci et al. in https://doi.org/10.3847/2041-8213/ac96e9:

> we must take into account that the stellar masses measured by the above authors have been inferred from luminosities assuming a ΛCDM cosmology to convert observed fluxes into luminosities.

That is,
$M_{\rm Mrbk}=(d_{l,\rm{Mrbk}}/d_{l,\rm{Labbe}})^2 \times M_{\rm Labbe}$,
where $d_l$ is the luminosity distance.
In your paper, the Planck 2020 cosmology was used. However, Labbe did not specify which parameters were used, so I guess he used the default parameters of 'EASY' (H0=70, Omega_m=0.3). The $(d_{l,\rm{Mike}}/d_{l,\rm{Labbe}})^2$ between the two universes differs by approximately 95%.

Best wishes,
Hois

**Comment by mrbk** [comment]
Dear Hois,

I think you must mean that the luminosity distance is different by a few percent (I get 2.5% for z=7.5), not 95% (or maybe you mean that the ratio of d^2 is 0.95, so the difference there is ~5%)? Yes, there will be small differences in the luminosity distance based on different cosmologies. The uncertainty coming from the cosmological model choice — of order 5% — is completely negligible compared to the other errors. Regardless, I haven’t converted the Labbe et al. luminosities (or stellar masses) into the Planck 2020 cosmology in what I’ve done.

Best regards,
Mike


--
Mike Boylan-Kolchin
Associate Professor  |  Department of Astronomy
The University of Texas at Austin
office: +1.512.471.3343
https://mrbk.github.io<https://www.as.utexas.edu/~mbk>

On May 14, 2023, at 9:20 AM, HoisW ***@***.***> wrote:



Thank you very much for your reply! If the data is directly from Dr. Ivo Labbe, this reminds me of another issue pointed out by N. Menci et al. in https://doi.org/10.3847/2041-8213/ac96e9:

we must take into account that the stellar masses measured by the above authors have been inferred from luminosities assuming a ΛCDM cosmology to convert observed fluxes into luminosities.

That is,
$M_{\rm Mrbk}=(d_{l,\rm{Mrbk}}/d_{l,\rm{Labbe}})^2 \times M_{\rm Labbe}$,
where $d_l$ is the luminosity distance.
In your paper, the Planck 2020 cosmology was used. However, Labbe did not specify which parameters were used, so I guess he used the default parameters of 'EASY' (H0=70, Omega_m=0.3). The $(d_{l,\rm{Mike}}/d_{l,\rm{Labbe}})^2$ between the two universes differs by approximately 95%.

Best wishes,
Hois

**Comment by HoisW** [comment]
Sorry, I made a mistake.  The ratio of d^2 is (0.975)^2=0.95.
Compared with other errors, it is indeed negligible. Thank you for your guidance！
